In [2]:
import requests
from bs4 import BeautifulSoup
from lxml import html
        
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
%run helpers.py

In [9]:
#this is the search parameters that i will be searching in the website
#and i can keep extending list if i want to or specify it 

search_parameters=['informatics']#informatics doesn't have that many jobs so i used it as a test subject 

# the search parameters i used in my actual scraping:
# ['data', 'analysis', 'research','informatics','statistic','business intelligence']


#converting the search parameters to use in the url, meaing i will be placing the search terms in the url itself:
def replace(lists):
    for index, item in enumerate(lists):
        lists[index]=(item.replace(' ','-'))
    return lists

In [10]:
replace(search_parameters)

# converted list
search_parameters

['data',
 'analysis',
 'research',
 'informatics',
 'statistic',
 'business-intelligence']

the reason i used only 6 search parameters is that i believed that these phrases were enough to cover all data-related jobs from all fields

also i have set it up in a manner that i can re-use the same code for different job fields and even specific search terms in the future without significant or no change to the code.(just change the search terms and BoB's your Uncle)

I used 12 different features that i thought would we useful in the analysis and questions that they might be able to answer:

1)title: This is neccessary for the project itself

2)salary: agan it is neccessary 

3)location: where are the data related jobs and where the higher salaries might be

4)area(specific area within location): do specific areas withnin each location impact title and salaries

5)class(industry): does the industry determine the salary and titles

6)sub-class(sub-industry): does the sub-industry play a significant role or not 

7)type: is there a title or salary difference in terms of Fulltime,parttime,etc

8)date: does the dates of the jobs being posted impact the salary and title

9)description: what kind of description exists for data scientist roles and does it impact salary

10)job_id :this is only there to get rid of duplicate jobs

11)level: this is a recommendation job by seek themselves and does this make a difference or not

12)company: there are many companies out there and help determine which company post what kind of jobs and the amount of salary


Now i know that i probabaly won't be able to answer all questions and that not all features would be useful but i will need to figure that out by doing some analysis.

In [ ]:
# Now for the main course:
# here i will be searching all the search parameters and getting the jobs for each search parameter



# creating a dataframe and its index 
# and a temporary dictioonary
data=None
index=1 
temp_article={}

# looping through the search parameters and placing in in the url to get the jobs for each search parameter
for item in search_parameters:
    
    print item #this will give me a count and progress info of the scraping
    
    url='https://www.seek.com.au/%s-jobs?page='%item #placing in url
    
    #calculating how many pages to go through by getting the job number shown(search result number) on the site and dividing it up by 20
    # because there are 20 jobs per page
    #however the limit is 500m pages on the website so if the search result number shown has more jobs than 500 pages 
    #it will only look for 500 pages and jobs on only 500 pages 
    
    #getting the url for the search parameter
    r = requests.get(url)
    #turning it into a html doc
    html0=html.document_fromstring(r.text)
    #locating the 'job number'(serach result number) listed for the search parameter using xpath
    search_page = html0.xpath('//*[@id="SearchSummary"]/strong')
    #looping through the search_page list:
    for job_number in search_page:
        
        #converting the number to a usable int and rounding it up with .9 and 
        # +1 to make include the number in the range 
        num=int(round(float(job_number.text.replace(',',''))/20.0+.9))+1
        if num>500:
            num = 500
        else:
            num=num

    print num  #this will give me a count and progress info of the scraping
    
    #looping thourgh each page
    for page in range(1,num):
        
        print page #this will give me a count and progress info of the scraping
        
        
        # make request for that page
        r = requests.get(url+str(page))

        # turn into a BeautifulSoup object
        soup = BeautifulSoup(r.text, 'lxml')


        # find job articles on page
        articles = soup.find_all(name='article')


        # iterating through each job on the main search page:
        for article in articles:
            
            #lookng for some feature that are not in the jobs page itself
            #desrciption,job_id and level

            #description feature:
            dvg=article.find_all(name='span', attrs={'class':"bl7UwXp"})
            for z in dvg:
                temp_article['description']=z.text

            #getting the job_id and level which an attribute of the html article code:
            temp_article['job_id']=article.attrs['data-job-id']
            temp_article['level']=article.attrs['data-automation']


            #finding the url for each job so that i can go to each jobs own page
            #and grab features straight from there
            dvg=article.find_all(name='a',attrs={'class':"_1EkZJQ7"})
            for z in dvg:
                
                #finding the url for the job's own page
                s=z.attrs['href']
                #requesting html for the job's page
                r = requests.get('https://www.seek.com.au'+s)
                #convering it to html file
                html1=html.document_fromstring(r.text)
                
                #finding the remaining attributes on the page itself using xpath and temporarily adding it
                #to the 'temp_article' dictionary


                #title
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[1]/div/div/section/div/div/span/span/h1')
                for z in dvg:
                    temp_article['title']=z.text



                #company       
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[1]/div/div/section/div/div/h2/span[2]/span')
                for z in dvg:
                    temp_article['company']=z.text


                #date
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/aside/span/div[1]/div/section/dl/dd[1]/span/span')
                for z in dvg:
                    temp_article['date']=z.text

                #location
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/dd[2]/span/span/strong')
                for z in dvg:
                    temp_article['location'] = z.text


                #salary
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/div[1]/dd/span/span')
                for z in dvg:
                    temp_article['salary']=z.text

                #area
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/aside/span/div[1]/div/section/dl/dd[2]/span/span/span/text()')
                for z in dvg:
                    temp_article['area']=z

                #type
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/dd[3]/span/span')
                for z in dvg:
                    temp_article['type']=z.text


                #class
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/aside/span/div[1]/div/section/dl/div/dd/span/span/strong')
                for z in dvg:
                    temp_article['class']=z.text

                #sub_class
                dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/div/dd/span/span/span/text()')
                for z in dvg:
                    temp_article['sub_class']=z




            #making the dataframe using the 'temp_article' dictionary, info created at the beginning of this code
            temp=pd.DataFrame(temp_article, index=[index])
            index+=1
            try:
                data=pd.concat([data,temp])

            except:
                data=temp

data
500
1
2
3
4
5
6
7
8
9
10
11
12

In [8]:
print data.shape
data.head()

(50, 12)

,area,class,company,date,description,job_id,level,location,salary,sub_class,title,type
1,NaN,Government & Defence,Metro North Hospital & Health Service,20 Dec 2017,Support Medical Imaging Informatics systems ma...,35125475,normalJob,Brisbane,$73 864 - $81 380 p.a.,Government - State,Informatics Officer,Contract/Temp
2,NaN,Administration & Office Support,Metro North Hospital & Health Service,20 Dec 2017,Support Medical Imaging Informatics systems ma...,35125474,normalJob,Brisbane,$73 864 - $81 380 p.a.,Office Management,Informatics Officer,Contract/Temp
3,NaN,Science & Technology,None,13 Dec 2017,"- Full-time, fixed-term appointment for 12 mon...",35084230,normalJob,Ballarat & Central Highlands,None,Other,"Research Associate, Climate Informatics",Full Time
4,NaN,Education & Training,None,12 Dec 2017,"- Full-time, fixed-term appointment for 12 mon...",35074788,normalJob,Ballarat & Central Highlands,None,Research & Fellowships,"Research Associate, Climate Informatics",Full Time
5,Northern Suburbs,Information & Communication Technology,None,15 Dec 2017,An exciting opportunity currently exists for a...,35096583,normalJob,Melbourne,None,Business/Systems Analysts,Cerner Clinical Analyst,Full Time

In [7]:
# saving it down as a excel file
# also i commented it out simply because i don't want it to overlap and create a new file

# data.to_excel('./scraped.xls')

In [8]:
#reloaded the file to check it out 

data2=pd.read_excel('./scraped.xls')

In [9]:
data2.head(30)

,area,class,company,date,description,job_id,level,location,salary,sub_class,title,type
1,NaN,NaN,NaN,NaN,Join a talented and dynamic team in multi-chan...,35046021,premiumJob,NaN,NaN,NaN,NaN,NaN
2,"CBD, Inner West & Eastern Suburbs",Information & Communication Technology,Energy & Water Ombudsman NSW,19 Dec 2017,Seeking an experienced desktop support analyst...,35118800,premiumJob,Sydney,NaN,Business/Systems Analysts,Data Analysis and Support Officer,Part Time
3,"CBD, Inner West & Eastern Suburbs",Information & Communication Technology,NaN,21 Dec 2017,Expertise in Data Architecture frameworks e.g....,35132539,normalJob,ACT,NaN,Architects,Data Architect,Contract/Temp
4,"CBD, Inner West & Eastern Suburbs",Healthcare & Medical,NaN,21 Dec 2017,"Analyse financial, human resource, service del...",35131963,normalJob,Townsville & Northern QLD,Great remuneration & benefits!,Management,Finance and Data Manager,Contract/Temp
5,"CBD, Inner West & Eastern Suburbs",Accounting,NaN,21 Dec 2017,"Analyse financial, human resource, service del...",35131964,normalJob,Townsville & Northern QLD,Great remuneration & benefits!,Management,Finance and Data Manager,Contract/Temp
6,Southern Suburbs & Logan,Administration & Office Support,Labour Solutions Australia,21 Dec 2017,"Our client, a leading Records Management compa...",35132583,normalJob,Brisbane,NaN,Records Management & Document Control,Records Admin / Data Entry - Process Workers -...,Casual/Vacation
7,Southern Suburbs & Logan,Information & Communication Technology,Opus Recruitment Solutions,21 Dec 2017,DATA SCIENCE SUPERSTARS\r\n\r\nMODERN OFFICES\...,35131268,normalJob,Sydney,$100000 - $220000 per annum,Database Development & Administration,Data Science Leads,Full Time
8,"CBD, Inner West & Eastern Suburbs",Information & Communication Technology,7 Recruitment,21 Dec 2017,Leading financial services leader are seeking ...,35130630,normalJob,Sydney,NaN,Business/Systems Analysts,Data Governance Manager,Full Time
9,Parramatta & Western Suburbs,Information & Communication Technology,Infinity Pro,21 Dec 2017,"Risk Data Insight Analyst - Control, Risk Data...",35130722,normalJob,Sydney,Great Rems + End User + Parking + Generous Bon...,Consultants,Risk Data Insight Analyst - Risk / Investigati...,Full Time
10,CBD & Inner Suburbs,Information & Communication Technology,Ampstek Australia Ptd LTD,21 Dec 2017,"Urgent Multiple Data Security with DLP, Infras...",35130579,normalJob,Melbourne,NaN,Security,"Urgent Multiple Data Security with DLP, Infras...",Contract/Temp
11,North Shore & Northern Beaches,Information & Communication Technology,Spark Recruitment,21 Dec 2017,Take ownership for the strategic development o...,35130098,normalJob,Sydney,$150k - $160k p.a. + bonus,Product Management & Development,Product Manager - Big Data / Data Analytics,Full Time
12,"CBD, Inner West & Eastern Suburbs",Government & Defence,NaN,21 Dec 2017,Exciting new role for a CSI Configuration and ...,35130193,normalJob,Sydney,NaN,Other,CSI Configuration and Data Management Officer,Full Time
13,Parramatta & Western Suburbs,Information & Communication Technology,Infinity Pro,21 Dec 2017,"SSIS, SSAS Business Intelligence / Data Wareho...",35130090,normalJob,Sydney,End User Company - Great Remuneration & Benefits,Consultants,Microsoft Business Intelligence Consultant - S...,Full Time
14,North Shore & Northern Beaches,Administration & Office Support,NaN,21 Dec 2017,Initial 12 month fixed term contract role to d...,35132045,normalJob,Sydney,NaN,Data Entry & Word Processing,Procurement Master Data Officer,Contract/Temp
15,North Shore & Northern Beaches,Information & Communication Technology,Mine Wealth + Wellbeing,21 Dec 2017,Exciting opportunity for Data Analyst!,35129716,normalJob,"Newcastle, Maitland & Hunter",NaN,Other,Data Analyst,Full Time
16,"CBD, Inner West & Eastern Suburbs",Information & Communication Technology,2XM Technology Pty Ltd,21 Dec 2017,Data Solution Architect required to work on a ...,35129596,normalJob,Sydney,$160-$200k + super,Architects,Big Data Solution Architect,Full Time
17,"CBD, Inner West & Eastern Suburbs",Information & Communication Technology,2XM Technology Pty Ltd,21 Dec 2017,Seeking experienced Data Analyst with strong S...,35129559,normalJob,Sydney,NaN,Developers/Programmers,Data Analyst - SQL Developer,Contract/Temp
18,"CBD, Inner West & Eastern Suburbs",Information & Communication Technology,NaN,21 Dec 2017,Our client is looking for an experienced Data ...,35129263,normalJob,Adelaide,NaN,Developers/Programmers,Data Warehouse Developer,Full Time
19,CBD & Inner Suburbs,Accounting,Hudson,21 Dec 2017,In this role you would be driving the robust u...,35129259,normalJob,Melbourne,Super,Systems Accounting & IT Audit,Senior Auditor- Data Analytics,Contract/Temp
20,CBD & Inner Suburbs,Engineering,Employment Office,21 Dec 2017,Are you an experienced Surveyor looking for an...,35131526,normalJob,Melbourne,"$70,000 - $95,000 plus super!",Project Engineering,Surveyor Data Manager,Full Time
21,CBD & Inner Suburbs,Engineering,Employment Office,21 Dec 2017,Are you an experienced Surveyor looking for an...,35131487,normalJob,Melbourne,"$70,000 - $95,000 plus super!",Civil/Structural Engineering,Surveyor Data Manager,Full Time
22,CBD & Inner Suburbs,Information & Communication Technology,Chandler Macleod Group,21 Dec 2017,ACT Location - Federal Government Client,35131028,normalJob,ACT,NaN,Database Development & Administration,Data Analyst,Contract/Temp
23,CBD & Inner Suburbs,Information & Communication Technology,PCM,6 Dec 2017,Outstanding opportunity for an experienced Dat...,35038594,premiumJob,Adelaide,NaN,Business/Systems Analysts,Data Science & Machine Learning Analyst,Full Time
24,CBD & Inner Suburbs,Science & Technology,Crypton Analytics,25 Nov 2017,The data scientist will explore large datasets...,34965080,premiumJob,Melbourne,"$90,000 - $119,999","Mathematics, Statistics & Information Sciences",Data Scientist (Cryptocurrency),Full Time
25,CBD & Inner Suburbs,Information & Communication Technology,Alitis,21 Dec 2017,Big Data Solution Architect with Retail indust...,35128414,normalJob,Sydney,NaN,Architects,Big Data Solution Architect,Contract/Temp
26,CBD & Inner Suburbs,Information & Communication Technology,NaN,21 Dec 2017,"Provide Data, Business Intelligence and Analyt...",35128322,normalJob,ACT,NaN,Architects,Data Warehouse Architect,Full Time
27,CBD & Inner Suburbs,Information & Communication Technology,Chandler Macleod Group,21 Dec 2017,ACT Location - Federal Government Client,35129184,normalJob,ACT,NaN,Database Development & Administration,Actuaries and Data Analysts,Contract/Temp
28,CBD & Inner Suburbs,Information & Communication Technology,Genesis IT&T P/L,21 Dec 2017,The Network Architect will be responsible for ...,35129133,normalJob,Melbourne,Competitive Salary Package,Architects,Network Architect - Data Centre | Campus | WAN,Full Time
29,North Shore & Northern Beaches,Information & Communication Technology,Chandler Macleod Group,21 Dec 2017,Manager Data Governance and Architecture,35132463,normalJob,Sydney,NaN,Management,Specialist Manager,Contract/Temp
30,"CBD, Inner West & Eastern Suburbs",Administration & Office Support,Sinclair Recruitment Pty Ltd,21 Dec 2017,Are YOU searching for a step into the Corporat...,35128429,normalJob,Sydney,Heaps of Social Perks!,Administrative Assistants,Administration & Data Entry Experts | Corporat...,Full Time

In [ ]:
#This is where is was trying alot of the stuff

In [ ]:

# make request for that page
r = requests.get('https://www.seek.com.au/informatics-jobs?page='+str(1))

# turn into a BeautifulSoup object
soup = BeautifulSoup(r.text, 'lxml')


# find job article on page
articles = soup.find_all(name='article')


# r = requests.get(url)
html0=html.document_fromstring(r.text)
search_page = html0.xpath('//*[@id="SearchSummary"]/strong')
for job_number in search_page:
    
    num=int(round(float(job_number.text.replace(',',''))/20.0+.9))+1
    if num>500:
        num = 500
    else:
        num=num
    print num
    print range(1,num)
    
# iterating through each job:
for article in articles:
    
    #description feature:
    dvg=article.find_all(name='span', attrs={'class':"bl7UwXp"})
    for z in dvg:
        temp_article['description']=z.text
    
    #getting the job_id and level which an attribute of the html article code:
    temp_article['job_id']=article.attrs['data-job-id']
    temp_article['level']=article.attrs['data-automation']
            
    
    #finding the url for each job so that i can to to each jobs page
    #and grab features straight from there
    dvg=article.find_all(name='a',attrs={'class':"_1EkZJQ7"})
    for z in dvg:

        s=z.attrs['href']

        r = requests.get('https://www.seek.com.au'+s)

        html1=html.document_fromstring(r.text)
        
        
        #title
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[1]/div/div/section/div/div/span/span/h1')
        for z in dvg:
            temp_article['title']=z.text
    


        #company       
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[1]/div/div/section/div/div/h2/span[2]/span')
        for z in dvg:
            temp_article['company']=z.text


        #date
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/aside/span/div[1]/div/section/dl/dd[1]/span/span')
        for z in dvg:
            temp_article['date']=z.text

        #location
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/dd[2]/span/span/strong')
        for z in dvg:
            temp_article['location'] = z.text
   

        #salary
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/div[1]/dd/span/span')
        for z in dvg:
            temp_article['salary']=z.text

        #area
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/aside/span/div[1]/div/section/dl/dd[2]/span/span/span/text()')
        for z in dvg:
            temp_article['area']=z
            
        #type
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/dd[3]/span/span')
        for z in dvg:
            temp_article['type']=z.text
            
            
        #class
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/aside/span/div[1]/div/section/dl/div/dd/span/span/strong')
        for z in dvg:
            temp_article['class']=z.text
            
        #sub_class
        dvg = html1.xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div/article/div/div[1]/div/section/dl/div/dd/span/span/span/text()')
        for z in dvg:
            temp_article['sub_class']=z

    
               
     
    #making the dataframe
    temp=pd.DataFrame(temp_article, index=[index])
    index+=1
    try:
        x=pd.concat([x,temp])
        
    except:
        x=temp

In [ ]:
x.head(20)